package com.xzx.xzxms.purchase.bean;

public class PurchaseProType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_pro_type.id
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_pro_type.type
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_pro_type.is_active
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_pro_type.operator
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_pro_type.time
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_pro_type.update_operator
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    private String updateOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_pro_type.update_time
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_pro_type.id
     *
     * @return the value of purchase_pro_type.id
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_pro_type.id
     *
     * @param id the value for purchase_pro_type.id
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_pro_type.type
     *
     * @return the value of purchase_pro_type.type
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_pro_type.type
     *
     * @param type the value for purchase_pro_type.type
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_pro_type.is_active
     *
     * @return the value of purchase_pro_type.is_active
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_pro_type.is_active
     *
     * @param isActive the value for purchase_pro_type.is_active
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_pro_type.operator
     *
     * @return the value of purchase_pro_type.operator
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_pro_type.operator
     *
     * @param operator the value for purchase_pro_type.operator
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_pro_type.time
     *
     * @return the value of purchase_pro_type.time
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_pro_type.time
     *
     * @param time the value for purchase_pro_type.time
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_pro_type.update_operator
     *
     * @return the value of purchase_pro_type.update_operator
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public String getUpdateOperator() {
        return updateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_pro_type.update_operator
     *
     * @param updateOperator the value for purchase_pro_type.update_operator
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public void setUpdateOperator(String updateOperator) {
        this.updateOperator = updateOperator == null ? null : updateOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_pro_type.update_time
     *
     * @return the value of purchase_pro_type.update_time
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_pro_type.update_time
     *
     * @param updateTime the value for purchase_pro_type.update_time
     *
     * @mbg.generated Mon Feb 22 14:09:43 CST 2021
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}