package com.xzx.xzxms.bean;

import java.util.ArrayList;
import java.util.List;

public class QuoteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public QuoteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNull() {
            addCriterion("supplier is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNotNull() {
            addCriterion("supplier is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierEqualTo(String value) {
            addCriterion("supplier =", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotEqualTo(String value) {
            addCriterion("supplier <>", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThan(String value) {
            addCriterion("supplier >", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("supplier >=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThan(String value) {
            addCriterion("supplier <", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThanOrEqualTo(String value) {
            addCriterion("supplier <=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLike(String value) {
            addCriterion("supplier like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotLike(String value) {
            addCriterion("supplier not like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierIn(List<String> values) {
            addCriterion("supplier in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotIn(List<String> values) {
            addCriterion("supplier not in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierBetween(String value1, String value2) {
            addCriterion("supplier between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotBetween(String value1, String value2) {
            addCriterion("supplier not between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andSuModelIsNull() {
            addCriterion("su_model is null");
            return (Criteria) this;
        }

        public Criteria andSuModelIsNotNull() {
            addCriterion("su_model is not null");
            return (Criteria) this;
        }

        public Criteria andSuModelEqualTo(String value) {
            addCriterion("su_model =", value, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelNotEqualTo(String value) {
            addCriterion("su_model <>", value, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelGreaterThan(String value) {
            addCriterion("su_model >", value, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelGreaterThanOrEqualTo(String value) {
            addCriterion("su_model >=", value, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelLessThan(String value) {
            addCriterion("su_model <", value, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelLessThanOrEqualTo(String value) {
            addCriterion("su_model <=", value, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelLike(String value) {
            addCriterion("su_model like", value, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelNotLike(String value) {
            addCriterion("su_model not like", value, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelIn(List<String> values) {
            addCriterion("su_model in", values, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelNotIn(List<String> values) {
            addCriterion("su_model not in", values, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelBetween(String value1, String value2) {
            addCriterion("su_model between", value1, value2, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuModelNotBetween(String value1, String value2) {
            addCriterion("su_model not between", value1, value2, "suModel");
            return (Criteria) this;
        }

        public Criteria andSuBrandIsNull() {
            addCriterion("su_brand is null");
            return (Criteria) this;
        }

        public Criteria andSuBrandIsNotNull() {
            addCriterion("su_brand is not null");
            return (Criteria) this;
        }

        public Criteria andSuBrandEqualTo(String value) {
            addCriterion("su_brand =", value, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandNotEqualTo(String value) {
            addCriterion("su_brand <>", value, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandGreaterThan(String value) {
            addCriterion("su_brand >", value, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandGreaterThanOrEqualTo(String value) {
            addCriterion("su_brand >=", value, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandLessThan(String value) {
            addCriterion("su_brand <", value, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandLessThanOrEqualTo(String value) {
            addCriterion("su_brand <=", value, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandLike(String value) {
            addCriterion("su_brand like", value, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandNotLike(String value) {
            addCriterion("su_brand not like", value, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandIn(List<String> values) {
            addCriterion("su_brand in", values, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandNotIn(List<String> values) {
            addCriterion("su_brand not in", values, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandBetween(String value1, String value2) {
            addCriterion("su_brand between", value1, value2, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuBrandNotBetween(String value1, String value2) {
            addCriterion("su_brand not between", value1, value2, "suBrand");
            return (Criteria) this;
        }

        public Criteria andSuParamsIsNull() {
            addCriterion("su_params is null");
            return (Criteria) this;
        }

        public Criteria andSuParamsIsNotNull() {
            addCriterion("su_params is not null");
            return (Criteria) this;
        }

        public Criteria andSuParamsEqualTo(String value) {
            addCriterion("su_params =", value, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsNotEqualTo(String value) {
            addCriterion("su_params <>", value, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsGreaterThan(String value) {
            addCriterion("su_params >", value, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsGreaterThanOrEqualTo(String value) {
            addCriterion("su_params >=", value, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsLessThan(String value) {
            addCriterion("su_params <", value, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsLessThanOrEqualTo(String value) {
            addCriterion("su_params <=", value, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsLike(String value) {
            addCriterion("su_params like", value, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsNotLike(String value) {
            addCriterion("su_params not like", value, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsIn(List<String> values) {
            addCriterion("su_params in", values, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsNotIn(List<String> values) {
            addCriterion("su_params not in", values, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsBetween(String value1, String value2) {
            addCriterion("su_params between", value1, value2, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuParamsNotBetween(String value1, String value2) {
            addCriterion("su_params not between", value1, value2, "suParams");
            return (Criteria) this;
        }

        public Criteria andSuPriceIsNull() {
            addCriterion("su_price is null");
            return (Criteria) this;
        }

        public Criteria andSuPriceIsNotNull() {
            addCriterion("su_price is not null");
            return (Criteria) this;
        }

        public Criteria andSuPriceEqualTo(Double value) {
            addCriterion("su_price =", value, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuPriceNotEqualTo(Double value) {
            addCriterion("su_price <>", value, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuPriceGreaterThan(Double value) {
            addCriterion("su_price >", value, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("su_price >=", value, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuPriceLessThan(Double value) {
            addCriterion("su_price <", value, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuPriceLessThanOrEqualTo(Double value) {
            addCriterion("su_price <=", value, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuPriceIn(List<Double> values) {
            addCriterion("su_price in", values, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuPriceNotIn(List<Double> values) {
            addCriterion("su_price not in", values, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuPriceBetween(Double value1, Double value2) {
            addCriterion("su_price between", value1, value2, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuPriceNotBetween(Double value1, Double value2) {
            addCriterion("su_price not between", value1, value2, "suPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceIsNull() {
            addCriterion("su_total_price is null");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceIsNotNull() {
            addCriterion("su_total_price is not null");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceEqualTo(Double value) {
            addCriterion("su_total_price =", value, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceNotEqualTo(Double value) {
            addCriterion("su_total_price <>", value, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceGreaterThan(Double value) {
            addCriterion("su_total_price >", value, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("su_total_price >=", value, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceLessThan(Double value) {
            addCriterion("su_total_price <", value, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceLessThanOrEqualTo(Double value) {
            addCriterion("su_total_price <=", value, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceIn(List<Double> values) {
            addCriterion("su_total_price in", values, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceNotIn(List<Double> values) {
            addCriterion("su_total_price not in", values, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceBetween(Double value1, Double value2) {
            addCriterion("su_total_price between", value1, value2, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuTotalPriceNotBetween(Double value1, Double value2) {
            addCriterion("su_total_price not between", value1, value2, "suTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryIsNull() {
            addCriterion("su_delivery is null");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryIsNotNull() {
            addCriterion("su_delivery is not null");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryEqualTo(Long value) {
            addCriterion("su_delivery =", value, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryNotEqualTo(Long value) {
            addCriterion("su_delivery <>", value, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryGreaterThan(Long value) {
            addCriterion("su_delivery >", value, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryGreaterThanOrEqualTo(Long value) {
            addCriterion("su_delivery >=", value, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryLessThan(Long value) {
            addCriterion("su_delivery <", value, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryLessThanOrEqualTo(Long value) {
            addCriterion("su_delivery <=", value, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryIn(List<Long> values) {
            addCriterion("su_delivery in", values, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryNotIn(List<Long> values) {
            addCriterion("su_delivery not in", values, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryBetween(Long value1, Long value2) {
            addCriterion("su_delivery between", value1, value2, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andSuDeliveryNotBetween(Long value1, Long value2) {
            addCriterion("su_delivery not between", value1, value2, "suDelivery");
            return (Criteria) this;
        }

        public Criteria andWarrantyIsNull() {
            addCriterion("warranty is null");
            return (Criteria) this;
        }

        public Criteria andWarrantyIsNotNull() {
            addCriterion("warranty is not null");
            return (Criteria) this;
        }

        public Criteria andWarrantyEqualTo(Long value) {
            addCriterion("warranty =", value, "warranty");
            return (Criteria) this;
        }

        public Criteria andWarrantyNotEqualTo(Long value) {
            addCriterion("warranty <>", value, "warranty");
            return (Criteria) this;
        }

        public Criteria andWarrantyGreaterThan(Long value) {
            addCriterion("warranty >", value, "warranty");
            return (Criteria) this;
        }

        public Criteria andWarrantyGreaterThanOrEqualTo(Long value) {
            addCriterion("warranty >=", value, "warranty");
            return (Criteria) this;
        }

        public Criteria andWarrantyLessThan(Long value) {
            addCriterion("warranty <", value, "warranty");
            return (Criteria) this;
        }

        public Criteria andWarrantyLessThanOrEqualTo(Long value) {
            addCriterion("warranty <=", value, "warranty");
            return (Criteria) this;
        }

        public Criteria andWarrantyIn(List<Long> values) {
            addCriterion("warranty in", values, "warranty");
            return (Criteria) this;
        }

        public Criteria andWarrantyNotIn(List<Long> values) {
            addCriterion("warranty not in", values, "warranty");
            return (Criteria) this;
        }

        public Criteria andWarrantyBetween(Long value1, Long value2) {
            addCriterion("warranty between", value1, value2, "warranty");
            return (Criteria) this;
        }

        public Criteria andWarrantyNotBetween(Long value1, Long value2) {
            addCriterion("warranty not between", value1, value2, "warranty");
            return (Criteria) this;
        }

        public Criteria andSuRemarkIsNull() {
            addCriterion("su_remark is null");
            return (Criteria) this;
        }

        public Criteria andSuRemarkIsNotNull() {
            addCriterion("su_remark is not null");
            return (Criteria) this;
        }

        public Criteria andSuRemarkEqualTo(String value) {
            addCriterion("su_remark =", value, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkNotEqualTo(String value) {
            addCriterion("su_remark <>", value, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkGreaterThan(String value) {
            addCriterion("su_remark >", value, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("su_remark >=", value, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkLessThan(String value) {
            addCriterion("su_remark <", value, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkLessThanOrEqualTo(String value) {
            addCriterion("su_remark <=", value, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkLike(String value) {
            addCriterion("su_remark like", value, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkNotLike(String value) {
            addCriterion("su_remark not like", value, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkIn(List<String> values) {
            addCriterion("su_remark in", values, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkNotIn(List<String> values) {
            addCriterion("su_remark not in", values, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkBetween(String value1, String value2) {
            addCriterion("su_remark between", value1, value2, "suRemark");
            return (Criteria) this;
        }

        public Criteria andSuRemarkNotBetween(String value1, String value2) {
            addCriterion("su_remark not between", value1, value2, "suRemark");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andInquiryIdIsNull() {
            addCriterion("inquiry_id is null");
            return (Criteria) this;
        }

        public Criteria andInquiryIdIsNotNull() {
            addCriterion("inquiry_id is not null");
            return (Criteria) this;
        }

        public Criteria andInquiryIdEqualTo(Long value) {
            addCriterion("inquiry_id =", value, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andInquiryIdNotEqualTo(Long value) {
            addCriterion("inquiry_id <>", value, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andInquiryIdGreaterThan(Long value) {
            addCriterion("inquiry_id >", value, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andInquiryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("inquiry_id >=", value, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andInquiryIdLessThan(Long value) {
            addCriterion("inquiry_id <", value, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andInquiryIdLessThanOrEqualTo(Long value) {
            addCriterion("inquiry_id <=", value, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andInquiryIdIn(List<Long> values) {
            addCriterion("inquiry_id in", values, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andInquiryIdNotIn(List<Long> values) {
            addCriterion("inquiry_id not in", values, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andInquiryIdBetween(Long value1, Long value2) {
            addCriterion("inquiry_id between", value1, value2, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andInquiryIdNotBetween(Long value1, Long value2) {
            addCriterion("inquiry_id not between", value1, value2, "inquiryId");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNull() {
            addCriterion("is_active is null");
            return (Criteria) this;
        }

        public Criteria andIsActiveIsNotNull() {
            addCriterion("is_active is not null");
            return (Criteria) this;
        }

        public Criteria andIsActiveEqualTo(Integer value) {
            addCriterion("is_active =", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotEqualTo(Integer value) {
            addCriterion("is_active <>", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThan(Integer value) {
            addCriterion("is_active >", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_active >=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThan(Integer value) {
            addCriterion("is_active <", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveLessThanOrEqualTo(Integer value) {
            addCriterion("is_active <=", value, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveIn(List<Integer> values) {
            addCriterion("is_active in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotIn(List<Integer> values) {
            addCriterion("is_active not in", values, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveBetween(Integer value1, Integer value2) {
            addCriterion("is_active between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsActiveNotBetween(Integer value1, Integer value2) {
            addCriterion("is_active not between", value1, value2, "isActive");
            return (Criteria) this;
        }

        public Criteria andIsUsefulIsNull() {
            addCriterion("is_useful is null");
            return (Criteria) this;
        }

        public Criteria andIsUsefulIsNotNull() {
            addCriterion("is_useful is not null");
            return (Criteria) this;
        }

        public Criteria andIsUsefulEqualTo(Integer value) {
            addCriterion("is_useful =", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulNotEqualTo(Integer value) {
            addCriterion("is_useful <>", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulGreaterThan(Integer value) {
            addCriterion("is_useful >", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_useful >=", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulLessThan(Integer value) {
            addCriterion("is_useful <", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulLessThanOrEqualTo(Integer value) {
            addCriterion("is_useful <=", value, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulIn(List<Integer> values) {
            addCriterion("is_useful in", values, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulNotIn(List<Integer> values) {
            addCriterion("is_useful not in", values, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulBetween(Integer value1, Integer value2) {
            addCriterion("is_useful between", value1, value2, "isUseful");
            return (Criteria) this;
        }

        public Criteria andIsUsefulNotBetween(Integer value1, Integer value2) {
            addCriterion("is_useful not between", value1, value2, "isUseful");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(Long value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(Long value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(Long value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(Long value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(Long value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<Long> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<Long> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(Long value1, Long value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(Long value1, Long value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Long value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Long value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Long value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Long value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Long value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Long> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Long> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Long value1, Long value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Long value1, Long value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quote
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quote
     *
     * @mbg.generated Tue Nov 03 15:18:52 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}