package com.xzx.xzxms.bean;

public class SysProType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_type.id
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_type.name
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_type.is_active
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_type.is_useful
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    private Integer isUseful;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_type.time
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_type.operator
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    private Long operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_type.type
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    private Long type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_type.id
     *
     * @return the value of sys_pro_type.id
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_type.id
     *
     * @param id the value for sys_pro_type.id
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_type.name
     *
     * @return the value of sys_pro_type.name
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_type.name
     *
     * @param name the value for sys_pro_type.name
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_type.is_active
     *
     * @return the value of sys_pro_type.is_active
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_type.is_active
     *
     * @param isActive the value for sys_pro_type.is_active
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_type.is_useful
     *
     * @return the value of sys_pro_type.is_useful
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public Integer getIsUseful() {
        return isUseful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_type.is_useful
     *
     * @param isUseful the value for sys_pro_type.is_useful
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public void setIsUseful(Integer isUseful) {
        this.isUseful = isUseful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_type.time
     *
     * @return the value of sys_pro_type.time
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_type.time
     *
     * @param time the value for sys_pro_type.time
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_type.operator
     *
     * @return the value of sys_pro_type.operator
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_type.operator
     *
     * @param operator the value for sys_pro_type.operator
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_type.type
     *
     * @return the value of sys_pro_type.type
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_type.type
     *
     * @param type the value for sys_pro_type.type
     *
     * @mbg.generated Wed Aug 19 16:33:19 CST 2020
     */
    public void setType(Long type) {
        this.type = type;
    }
}