package com.xzx.xzxms.bean;

import java.util.ArrayList;
import java.util.List;

public class SysProCheckExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public SysProCheckExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditIsNull() {
            addCriterion("technical_audit is null");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditIsNotNull() {
            addCriterion("technical_audit is not null");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditEqualTo(Integer value) {
            addCriterion("technical_audit =", value, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditNotEqualTo(Integer value) {
            addCriterion("technical_audit <>", value, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditGreaterThan(Integer value) {
            addCriterion("technical_audit >", value, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("technical_audit >=", value, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditLessThan(Integer value) {
            addCriterion("technical_audit <", value, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditLessThanOrEqualTo(Integer value) {
            addCriterion("technical_audit <=", value, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditIn(List<Integer> values) {
            addCriterion("technical_audit in", values, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditNotIn(List<Integer> values) {
            addCriterion("technical_audit not in", values, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditBetween(Integer value1, Integer value2) {
            addCriterion("technical_audit between", value1, value2, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("technical_audit not between", value1, value2, "technicalAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditIsNull() {
            addCriterion("business_audit is null");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditIsNotNull() {
            addCriterion("business_audit is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditEqualTo(Integer value) {
            addCriterion("business_audit =", value, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditNotEqualTo(Integer value) {
            addCriterion("business_audit <>", value, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditGreaterThan(Integer value) {
            addCriterion("business_audit >", value, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("business_audit >=", value, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditLessThan(Integer value) {
            addCriterion("business_audit <", value, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditLessThanOrEqualTo(Integer value) {
            addCriterion("business_audit <=", value, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditIn(List<Integer> values) {
            addCriterion("business_audit in", values, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditNotIn(List<Integer> values) {
            addCriterion("business_audit not in", values, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditBetween(Integer value1, Integer value2) {
            addCriterion("business_audit between", value1, value2, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andBusinessAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("business_audit not between", value1, value2, "businessAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditIsNull() {
            addCriterion("compare_audit is null");
            return (Criteria) this;
        }

        public Criteria andCompareAuditIsNotNull() {
            addCriterion("compare_audit is not null");
            return (Criteria) this;
        }

        public Criteria andCompareAuditEqualTo(Integer value) {
            addCriterion("compare_audit =", value, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditNotEqualTo(Integer value) {
            addCriterion("compare_audit <>", value, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditGreaterThan(Integer value) {
            addCriterion("compare_audit >", value, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("compare_audit >=", value, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditLessThan(Integer value) {
            addCriterion("compare_audit <", value, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditLessThanOrEqualTo(Integer value) {
            addCriterion("compare_audit <=", value, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditIn(List<Integer> values) {
            addCriterion("compare_audit in", values, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditNotIn(List<Integer> values) {
            addCriterion("compare_audit not in", values, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditBetween(Integer value1, Integer value2) {
            addCriterion("compare_audit between", value1, value2, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andCompareAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("compare_audit not between", value1, value2, "compareAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditIsNull() {
            addCriterion("finally_audit is null");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditIsNotNull() {
            addCriterion("finally_audit is not null");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditEqualTo(Integer value) {
            addCriterion("finally_audit =", value, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditNotEqualTo(Integer value) {
            addCriterion("finally_audit <>", value, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditGreaterThan(Integer value) {
            addCriterion("finally_audit >", value, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("finally_audit >=", value, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditLessThan(Integer value) {
            addCriterion("finally_audit <", value, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditLessThanOrEqualTo(Integer value) {
            addCriterion("finally_audit <=", value, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditIn(List<Integer> values) {
            addCriterion("finally_audit in", values, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditNotIn(List<Integer> values) {
            addCriterion("finally_audit not in", values, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditBetween(Integer value1, Integer value2) {
            addCriterion("finally_audit between", value1, value2, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andFinallyAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("finally_audit not between", value1, value2, "finallyAudit");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkIsNull() {
            addCriterion("technical_remark is null");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkIsNotNull() {
            addCriterion("technical_remark is not null");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkEqualTo(String value) {
            addCriterion("technical_remark =", value, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkNotEqualTo(String value) {
            addCriterion("technical_remark <>", value, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkGreaterThan(String value) {
            addCriterion("technical_remark >", value, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("technical_remark >=", value, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkLessThan(String value) {
            addCriterion("technical_remark <", value, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkLessThanOrEqualTo(String value) {
            addCriterion("technical_remark <=", value, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkLike(String value) {
            addCriterion("technical_remark like", value, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkNotLike(String value) {
            addCriterion("technical_remark not like", value, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkIn(List<String> values) {
            addCriterion("technical_remark in", values, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkNotIn(List<String> values) {
            addCriterion("technical_remark not in", values, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkBetween(String value1, String value2) {
            addCriterion("technical_remark between", value1, value2, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andTechnicalRemarkNotBetween(String value1, String value2) {
            addCriterion("technical_remark not between", value1, value2, "technicalRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkIsNull() {
            addCriterion("business_remark is null");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkIsNotNull() {
            addCriterion("business_remark is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkEqualTo(String value) {
            addCriterion("business_remark =", value, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkNotEqualTo(String value) {
            addCriterion("business_remark <>", value, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkGreaterThan(String value) {
            addCriterion("business_remark >", value, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("business_remark >=", value, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkLessThan(String value) {
            addCriterion("business_remark <", value, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkLessThanOrEqualTo(String value) {
            addCriterion("business_remark <=", value, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkLike(String value) {
            addCriterion("business_remark like", value, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkNotLike(String value) {
            addCriterion("business_remark not like", value, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkIn(List<String> values) {
            addCriterion("business_remark in", values, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkNotIn(List<String> values) {
            addCriterion("business_remark not in", values, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkBetween(String value1, String value2) {
            addCriterion("business_remark between", value1, value2, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andBusinessRemarkNotBetween(String value1, String value2) {
            addCriterion("business_remark not between", value1, value2, "businessRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkIsNull() {
            addCriterion("compare_remark is null");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkIsNotNull() {
            addCriterion("compare_remark is not null");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkEqualTo(String value) {
            addCriterion("compare_remark =", value, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkNotEqualTo(String value) {
            addCriterion("compare_remark <>", value, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkGreaterThan(String value) {
            addCriterion("compare_remark >", value, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("compare_remark >=", value, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkLessThan(String value) {
            addCriterion("compare_remark <", value, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkLessThanOrEqualTo(String value) {
            addCriterion("compare_remark <=", value, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkLike(String value) {
            addCriterion("compare_remark like", value, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkNotLike(String value) {
            addCriterion("compare_remark not like", value, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkIn(List<String> values) {
            addCriterion("compare_remark in", values, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkNotIn(List<String> values) {
            addCriterion("compare_remark not in", values, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkBetween(String value1, String value2) {
            addCriterion("compare_remark between", value1, value2, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andCompareRemarkNotBetween(String value1, String value2) {
            addCriterion("compare_remark not between", value1, value2, "compareRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkIsNull() {
            addCriterion("finally_remark is null");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkIsNotNull() {
            addCriterion("finally_remark is not null");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkEqualTo(String value) {
            addCriterion("finally_remark =", value, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkNotEqualTo(String value) {
            addCriterion("finally_remark <>", value, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkGreaterThan(String value) {
            addCriterion("finally_remark >", value, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("finally_remark >=", value, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkLessThan(String value) {
            addCriterion("finally_remark <", value, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkLessThanOrEqualTo(String value) {
            addCriterion("finally_remark <=", value, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkLike(String value) {
            addCriterion("finally_remark like", value, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkNotLike(String value) {
            addCriterion("finally_remark not like", value, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkIn(List<String> values) {
            addCriterion("finally_remark in", values, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkNotIn(List<String> values) {
            addCriterion("finally_remark not in", values, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkBetween(String value1, String value2) {
            addCriterion("finally_remark between", value1, value2, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andFinallyRemarkNotBetween(String value1, String value2) {
            addCriterion("finally_remark not between", value1, value2, "finallyRemark");
            return (Criteria) this;
        }

        public Criteria andQuoteIdIsNull() {
            addCriterion("quote_id is null");
            return (Criteria) this;
        }

        public Criteria andQuoteIdIsNotNull() {
            addCriterion("quote_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuoteIdEqualTo(Long value) {
            addCriterion("quote_id =", value, "quoteId");
            return (Criteria) this;
        }

        public Criteria andQuoteIdNotEqualTo(Long value) {
            addCriterion("quote_id <>", value, "quoteId");
            return (Criteria) this;
        }

        public Criteria andQuoteIdGreaterThan(Long value) {
            addCriterion("quote_id >", value, "quoteId");
            return (Criteria) this;
        }

        public Criteria andQuoteIdGreaterThanOrEqualTo(Long value) {
            addCriterion("quote_id >=", value, "quoteId");
            return (Criteria) this;
        }

        public Criteria andQuoteIdLessThan(Long value) {
            addCriterion("quote_id <", value, "quoteId");
            return (Criteria) this;
        }

        public Criteria andQuoteIdLessThanOrEqualTo(Long value) {
            addCriterion("quote_id <=", value, "quoteId");
            return (Criteria) this;
        }

        public Criteria andQuoteIdIn(List<Long> values) {
            addCriterion("quote_id in", values, "quoteId");
            return (Criteria) this;
        }

        public Criteria andQuoteIdNotIn(List<Long> values) {
            addCriterion("quote_id not in", values, "quoteId");
            return (Criteria) this;
        }

        public Criteria andQuoteIdBetween(Long value1, Long value2) {
            addCriterion("quote_id between", value1, value2, "quoteId");
            return (Criteria) this;
        }

        public Criteria andQuoteIdNotBetween(Long value1, Long value2) {
            addCriterion("quote_id not between", value1, value2, "quoteId");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(Long value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(Long value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(Long value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(Long value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(Long value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<Long> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<Long> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(Long value1, Long value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(Long value1, Long value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Long value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Long value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Long value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Long value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Long value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Long> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Long> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Long value1, Long value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Long value1, Long value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_pro_check
     *
     * @mbg.generated do_not_delete_during_merge Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_pro_check
     *
     * @mbg.generated Sat Nov 14 10:20:12 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}