package com.xzx.xzxms.bean;

public class SysProCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_check.id
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_check.check_status
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    private Integer checkStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_check.type
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_check.remark
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_check.content_id
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    private Long contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_check.operator
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    private Long operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_pro_check.time
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    private Long time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_check.id
     *
     * @return the value of sys_pro_check.id
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_check.id
     *
     * @param id the value for sys_pro_check.id
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_check.check_status
     *
     * @return the value of sys_pro_check.check_status
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public Integer getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_check.check_status
     *
     * @param checkStatus the value for sys_pro_check.check_status
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_check.type
     *
     * @return the value of sys_pro_check.type
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_check.type
     *
     * @param type the value for sys_pro_check.type
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_check.remark
     *
     * @return the value of sys_pro_check.remark
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_check.remark
     *
     * @param remark the value for sys_pro_check.remark
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_check.content_id
     *
     * @return the value of sys_pro_check.content_id
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_check.content_id
     *
     * @param contentId the value for sys_pro_check.content_id
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_check.operator
     *
     * @return the value of sys_pro_check.operator
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_check.operator
     *
     * @param operator the value for sys_pro_check.operator
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_pro_check.time
     *
     * @return the value of sys_pro_check.time
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_pro_check.time
     *
     * @param time the value for sys_pro_check.time
     *
     * @mbg.generated Sat Nov 14 09:08:45 GMT+08:00 2020
     */
    public void setTime(Long time) {
        this.time = time;
    }
}