package com.xzx.xzxms.bean;

public class SysUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.id
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.user_id
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.role_id
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.is_active
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.is_useful
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    private Integer isUseful;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.operator
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    private Long operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.time
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    private Long time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.id
     *
     * @return the value of sys_user_role.id
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.id
     *
     * @param id the value for sys_user_role.id
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.user_id
     *
     * @return the value of sys_user_role.user_id
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.user_id
     *
     * @param userId the value for sys_user_role.user_id
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.role_id
     *
     * @return the value of sys_user_role.role_id
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.role_id
     *
     * @param roleId the value for sys_user_role.role_id
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.is_active
     *
     * @return the value of sys_user_role.is_active
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.is_active
     *
     * @param isActive the value for sys_user_role.is_active
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.is_useful
     *
     * @return the value of sys_user_role.is_useful
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public Integer getIsUseful() {
        return isUseful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.is_useful
     *
     * @param isUseful the value for sys_user_role.is_useful
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public void setIsUseful(Integer isUseful) {
        this.isUseful = isUseful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.operator
     *
     * @return the value of sys_user_role.operator
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.operator
     *
     * @param operator the value for sys_user_role.operator
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.time
     *
     * @return the value of sys_user_role.time
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.time
     *
     * @param time the value for sys_user_role.time
     *
<<<<<<< HEAD
     * @mbg.generated Tue Sep 08 21:15:37 CST 2020
=======
     * @mbg.generated Thu Sep 10 10:28:07 CST 2020
>>>>>>> a7352bdc1cd51076843a8a490f6672ec4b2b55bc
     */
    public void setTime(Long time) {
        this.time = time;
    }
}