package com.xzx.xzxms.inquiry.dao;

import com.xzx.xzxms.inquiry.bean.SysProType;
import com.xzx.xzxms.inquiry.bean.SysProTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysProTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    long countByExample(SysProTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    int deleteByExample(SysProTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    int insert(SysProType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    int insertSelective(SysProType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    List<SysProType> selectByExample(SysProTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    SysProType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    int updateByExampleSelective(@Param("record") SysProType record, @Param("example") SysProTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    int updateByExample(@Param("record") SysProType record, @Param("example") SysProTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    int updateByPrimaryKeySelective(SysProType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_pro_type
     *
     * @mbg.generated Tue Jan 05 19:42:53 CST 2021
     */
    int updateByPrimaryKey(SysProType record);
}