package com.xzx.xzxms.purchase.dao;

import com.xzx.xzxms.purchase.bean.ContractAudit;
import com.xzx.xzxms.purchase.bean.ContractAuditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    long countByExample(ContractAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    int deleteByExample(ContractAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    int insert(ContractAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    int insertSelective(ContractAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    List<ContractAudit> selectByExample(ContractAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    ContractAudit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    int updateByExampleSelective(@Param("record") ContractAudit record, @Param("example") ContractAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    int updateByExample(@Param("record") ContractAudit record, @Param("example") ContractAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    int updateByPrimaryKeySelective(ContractAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_audit
     *
     * @mbg.generated Tue Jan 12 10:46:37 CST 2021
     */
    int updateByPrimaryKey(ContractAudit record);
}