package com.xzx.xzxms.purchase.dao;

import com.xzx.xzxms.purchase.bean.PurchaseContractAccount;
import com.xzx.xzxms.purchase.bean.PurchaseContractAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurchaseContractAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    long countByExample(PurchaseContractAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    int deleteByExample(PurchaseContractAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    int insert(PurchaseContractAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    int insertSelective(PurchaseContractAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    List<PurchaseContractAccount> selectByExample(PurchaseContractAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    PurchaseContractAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") PurchaseContractAccount record, @Param("example") PurchaseContractAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    int updateByExample(@Param("record") PurchaseContractAccount record, @Param("example") PurchaseContractAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    int updateByPrimaryKeySelective(PurchaseContractAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_contract_account
     *
     * @mbg.generated Tue Jan 05 19:43:42 CST 2021
     */
    int updateByPrimaryKey(PurchaseContractAccount record);
}