package com.xzx.xzxms.equipment.dao;

import com.xzx.xzxms.equipment.bean.EquipmentOutStorage;
import com.xzx.xzxms.equipment.bean.EquipmentOutStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquipmentOutStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    long countByExample(EquipmentOutStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    int deleteByExample(EquipmentOutStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    int insert(EquipmentOutStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    int insertSelective(EquipmentOutStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    List<EquipmentOutStorage> selectByExample(EquipmentOutStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    EquipmentOutStorage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    int updateByExampleSelective(@Param("record") EquipmentOutStorage record, @Param("example") EquipmentOutStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    int updateByExample(@Param("record") EquipmentOutStorage record, @Param("example") EquipmentOutStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    int updateByPrimaryKeySelective(EquipmentOutStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_out_storage
     *
     * @mbg.generated Sun Jan 24 11:16:56 CST 2021
     */
    int updateByPrimaryKey(EquipmentOutStorage record);
}