package com.xzx.xzxms.equipment.dao;

import com.xzx.xzxms.equipment.bean.equipmentOrderStatus;
import com.xzx.xzxms.equipment.bean.equipmentOrderStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface equipmentOrderStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    long countByExample(equipmentOrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int deleteByExample(equipmentOrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int insert(equipmentOrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int insertSelective(equipmentOrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    List<equipmentOrderStatus> selectByExample(equipmentOrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    equipmentOrderStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") equipmentOrderStatus record, @Param("example") equipmentOrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int updateByExample(@Param("record") equipmentOrderStatus record, @Param("example") equipmentOrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int updateByPrimaryKeySelective(equipmentOrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_order_status
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int updateByPrimaryKey(equipmentOrderStatus record);
}