package com.xzx.xzxms.equipment.dao;

import com.xzx.xzxms.equipment.bean.equipmentInStorage;
import com.xzx.xzxms.equipment.bean.equipmentInStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface equipmentInStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    long countByExample(equipmentInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int deleteByExample(equipmentInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int insert(equipmentInStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int insertSelective(equipmentInStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    List<equipmentInStorage> selectByExample(equipmentInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    equipmentInStorage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") equipmentInStorage record, @Param("example") equipmentInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int updateByExample(@Param("record") equipmentInStorage record, @Param("example") equipmentInStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int updateByPrimaryKeySelective(equipmentInStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_in_storage
     *
     * @mbg.generated Sat Jan 23 12:46:02 CST 2021
     */
    int updateByPrimaryKey(equipmentInStorage record);
}