package com.xzx.xzxms.recruit.bean;

public class RecruitProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.id
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.project_name
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.content
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.stop_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.business_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String businessSender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.business_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Integer businessAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.business_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String businessOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.business_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long businessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.business_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String businessRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.engineering_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String engineeringSender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.engineering_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Integer engineeringAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.engineering_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String engineeringOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.engineering_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long engineeringTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.engineering_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String engineeringRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.release_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String releaseSender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.release_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Integer releaseAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.release_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String releaseOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.release_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long releaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.release_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String releaseRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.qualification_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String qualificationSender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.qualification_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Integer qualificationAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.qualification_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String qualificationOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.qualification_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long qualificationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.qualification_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String qualificationRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.bid_evaluation_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String bidEvaluationSender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.bid_evaluation_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Integer bidEvaluationAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.bid_evaluation_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String bidEvaluationOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.bid_evaluation_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long bidEvaluationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.bid_evaluation_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String bidEvaluationRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.report_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String reportSender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.report_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Integer reportAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.report_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String reportOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.report_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long reportTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.report_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String reportRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.successful_bidder
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String successfulBidder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.bid_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long bidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.is_active
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.update_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private String updateOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_project.update_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.id
     *
     * @return the value of recruit_project.id
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.id
     *
     * @param id the value for recruit_project.id
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.project_name
     *
     * @return the value of recruit_project.project_name
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.project_name
     *
     * @param projectName the value for recruit_project.project_name
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.content
     *
     * @return the value of recruit_project.content
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.content
     *
     * @param content the value for recruit_project.content
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.stop_time
     *
     * @return the value of recruit_project.stop_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.stop_time
     *
     * @param stopTime the value for recruit_project.stop_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setStopTime(Long stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.business_sender
     *
     * @return the value of recruit_project.business_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getBusinessSender() {
        return businessSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.business_sender
     *
     * @param businessSender the value for recruit_project.business_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBusinessSender(String businessSender) {
        this.businessSender = businessSender == null ? null : businessSender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.business_audit
     *
     * @return the value of recruit_project.business_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Integer getBusinessAudit() {
        return businessAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.business_audit
     *
     * @param businessAudit the value for recruit_project.business_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBusinessAudit(Integer businessAudit) {
        this.businessAudit = businessAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.business_operator
     *
     * @return the value of recruit_project.business_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getBusinessOperator() {
        return businessOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.business_operator
     *
     * @param businessOperator the value for recruit_project.business_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBusinessOperator(String businessOperator) {
        this.businessOperator = businessOperator == null ? null : businessOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.business_time
     *
     * @return the value of recruit_project.business_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getBusinessTime() {
        return businessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.business_time
     *
     * @param businessTime the value for recruit_project.business_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBusinessTime(Long businessTime) {
        this.businessTime = businessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.business_remark
     *
     * @return the value of recruit_project.business_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getBusinessRemark() {
        return businessRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.business_remark
     *
     * @param businessRemark the value for recruit_project.business_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBusinessRemark(String businessRemark) {
        this.businessRemark = businessRemark == null ? null : businessRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.engineering_sender
     *
     * @return the value of recruit_project.engineering_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getEngineeringSender() {
        return engineeringSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.engineering_sender
     *
     * @param engineeringSender the value for recruit_project.engineering_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setEngineeringSender(String engineeringSender) {
        this.engineeringSender = engineeringSender == null ? null : engineeringSender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.engineering_audit
     *
     * @return the value of recruit_project.engineering_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Integer getEngineeringAudit() {
        return engineeringAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.engineering_audit
     *
     * @param engineeringAudit the value for recruit_project.engineering_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setEngineeringAudit(Integer engineeringAudit) {
        this.engineeringAudit = engineeringAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.engineering_operator
     *
     * @return the value of recruit_project.engineering_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getEngineeringOperator() {
        return engineeringOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.engineering_operator
     *
     * @param engineeringOperator the value for recruit_project.engineering_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setEngineeringOperator(String engineeringOperator) {
        this.engineeringOperator = engineeringOperator == null ? null : engineeringOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.engineering_time
     *
     * @return the value of recruit_project.engineering_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getEngineeringTime() {
        return engineeringTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.engineering_time
     *
     * @param engineeringTime the value for recruit_project.engineering_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setEngineeringTime(Long engineeringTime) {
        this.engineeringTime = engineeringTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.engineering_remark
     *
     * @return the value of recruit_project.engineering_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getEngineeringRemark() {
        return engineeringRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.engineering_remark
     *
     * @param engineeringRemark the value for recruit_project.engineering_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setEngineeringRemark(String engineeringRemark) {
        this.engineeringRemark = engineeringRemark == null ? null : engineeringRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.release_sender
     *
     * @return the value of recruit_project.release_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getReleaseSender() {
        return releaseSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.release_sender
     *
     * @param releaseSender the value for recruit_project.release_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReleaseSender(String releaseSender) {
        this.releaseSender = releaseSender == null ? null : releaseSender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.release_audit
     *
     * @return the value of recruit_project.release_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Integer getReleaseAudit() {
        return releaseAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.release_audit
     *
     * @param releaseAudit the value for recruit_project.release_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReleaseAudit(Integer releaseAudit) {
        this.releaseAudit = releaseAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.release_operator
     *
     * @return the value of recruit_project.release_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getReleaseOperator() {
        return releaseOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.release_operator
     *
     * @param releaseOperator the value for recruit_project.release_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReleaseOperator(String releaseOperator) {
        this.releaseOperator = releaseOperator == null ? null : releaseOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.release_time
     *
     * @return the value of recruit_project.release_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.release_time
     *
     * @param releaseTime the value for recruit_project.release_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReleaseTime(Long releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.release_remark
     *
     * @return the value of recruit_project.release_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getReleaseRemark() {
        return releaseRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.release_remark
     *
     * @param releaseRemark the value for recruit_project.release_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReleaseRemark(String releaseRemark) {
        this.releaseRemark = releaseRemark == null ? null : releaseRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.qualification_sender
     *
     * @return the value of recruit_project.qualification_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getQualificationSender() {
        return qualificationSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.qualification_sender
     *
     * @param qualificationSender the value for recruit_project.qualification_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setQualificationSender(String qualificationSender) {
        this.qualificationSender = qualificationSender == null ? null : qualificationSender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.qualification_audit
     *
     * @return the value of recruit_project.qualification_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Integer getQualificationAudit() {
        return qualificationAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.qualification_audit
     *
     * @param qualificationAudit the value for recruit_project.qualification_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setQualificationAudit(Integer qualificationAudit) {
        this.qualificationAudit = qualificationAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.qualification_operator
     *
     * @return the value of recruit_project.qualification_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getQualificationOperator() {
        return qualificationOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.qualification_operator
     *
     * @param qualificationOperator the value for recruit_project.qualification_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setQualificationOperator(String qualificationOperator) {
        this.qualificationOperator = qualificationOperator == null ? null : qualificationOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.qualification_time
     *
     * @return the value of recruit_project.qualification_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getQualificationTime() {
        return qualificationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.qualification_time
     *
     * @param qualificationTime the value for recruit_project.qualification_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setQualificationTime(Long qualificationTime) {
        this.qualificationTime = qualificationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.qualification_remark
     *
     * @return the value of recruit_project.qualification_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getQualificationRemark() {
        return qualificationRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.qualification_remark
     *
     * @param qualificationRemark the value for recruit_project.qualification_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setQualificationRemark(String qualificationRemark) {
        this.qualificationRemark = qualificationRemark == null ? null : qualificationRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.bid_evaluation_sender
     *
     * @return the value of recruit_project.bid_evaluation_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getBidEvaluationSender() {
        return bidEvaluationSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.bid_evaluation_sender
     *
     * @param bidEvaluationSender the value for recruit_project.bid_evaluation_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBidEvaluationSender(String bidEvaluationSender) {
        this.bidEvaluationSender = bidEvaluationSender == null ? null : bidEvaluationSender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.bid_evaluation_audit
     *
     * @return the value of recruit_project.bid_evaluation_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Integer getBidEvaluationAudit() {
        return bidEvaluationAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.bid_evaluation_audit
     *
     * @param bidEvaluationAudit the value for recruit_project.bid_evaluation_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBidEvaluationAudit(Integer bidEvaluationAudit) {
        this.bidEvaluationAudit = bidEvaluationAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.bid_evaluation_operator
     *
     * @return the value of recruit_project.bid_evaluation_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getBidEvaluationOperator() {
        return bidEvaluationOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.bid_evaluation_operator
     *
     * @param bidEvaluationOperator the value for recruit_project.bid_evaluation_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBidEvaluationOperator(String bidEvaluationOperator) {
        this.bidEvaluationOperator = bidEvaluationOperator == null ? null : bidEvaluationOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.bid_evaluation_time
     *
     * @return the value of recruit_project.bid_evaluation_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getBidEvaluationTime() {
        return bidEvaluationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.bid_evaluation_time
     *
     * @param bidEvaluationTime the value for recruit_project.bid_evaluation_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBidEvaluationTime(Long bidEvaluationTime) {
        this.bidEvaluationTime = bidEvaluationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.bid_evaluation_remark
     *
     * @return the value of recruit_project.bid_evaluation_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getBidEvaluationRemark() {
        return bidEvaluationRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.bid_evaluation_remark
     *
     * @param bidEvaluationRemark the value for recruit_project.bid_evaluation_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBidEvaluationRemark(String bidEvaluationRemark) {
        this.bidEvaluationRemark = bidEvaluationRemark == null ? null : bidEvaluationRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.report_sender
     *
     * @return the value of recruit_project.report_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getReportSender() {
        return reportSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.report_sender
     *
     * @param reportSender the value for recruit_project.report_sender
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReportSender(String reportSender) {
        this.reportSender = reportSender == null ? null : reportSender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.report_audit
     *
     * @return the value of recruit_project.report_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Integer getReportAudit() {
        return reportAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.report_audit
     *
     * @param reportAudit the value for recruit_project.report_audit
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReportAudit(Integer reportAudit) {
        this.reportAudit = reportAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.report_operator
     *
     * @return the value of recruit_project.report_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getReportOperator() {
        return reportOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.report_operator
     *
     * @param reportOperator the value for recruit_project.report_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReportOperator(String reportOperator) {
        this.reportOperator = reportOperator == null ? null : reportOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.report_time
     *
     * @return the value of recruit_project.report_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.report_time
     *
     * @param reportTime the value for recruit_project.report_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReportTime(Long reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.report_remark
     *
     * @return the value of recruit_project.report_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getReportRemark() {
        return reportRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.report_remark
     *
     * @param reportRemark the value for recruit_project.report_remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setReportRemark(String reportRemark) {
        this.reportRemark = reportRemark == null ? null : reportRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.successful_bidder
     *
     * @return the value of recruit_project.successful_bidder
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getSuccessfulBidder() {
        return successfulBidder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.successful_bidder
     *
     * @param successfulBidder the value for recruit_project.successful_bidder
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setSuccessfulBidder(String successfulBidder) {
        this.successfulBidder = successfulBidder == null ? null : successfulBidder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.bid_time
     *
     * @return the value of recruit_project.bid_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getBidTime() {
        return bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.bid_time
     *
     * @param bidTime the value for recruit_project.bid_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setBidTime(Long bidTime) {
        this.bidTime = bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.is_active
     *
     * @return the value of recruit_project.is_active
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.is_active
     *
     * @param isActive the value for recruit_project.is_active
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.remark
     *
     * @return the value of recruit_project.remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.remark
     *
     * @param remark the value for recruit_project.remark
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.operator
     *
     * @return the value of recruit_project.operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.operator
     *
     * @param operator the value for recruit_project.operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.time
     *
     * @return the value of recruit_project.time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.time
     *
     * @param time the value for recruit_project.time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.update_operator
     *
     * @return the value of recruit_project.update_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public String getUpdateOperator() {
        return updateOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.update_operator
     *
     * @param updateOperator the value for recruit_project.update_operator
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setUpdateOperator(String updateOperator) {
        this.updateOperator = updateOperator == null ? null : updateOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_project.update_time
     *
     * @return the value of recruit_project.update_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_project.update_time
     *
     * @param updateTime the value for recruit_project.update_time
     *
     * @mbg.generated Sat Feb 20 11:10:15 CST 2021
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}